version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - mv target/*.jar aws-build-project.jar
      - echo build
  post_build:
    commands:
      - echo post_build

artifacts:
  files:
    - aws-build-project.jar
